export const globals = {
  defaultLanguage: 'en',
  promotionId: '50',
  token: "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJQbGF5ZXJJZCI6IjEzIiwiVXNlck5hbWUiOiJNYXJpYW1UZXN0IiwiU2VnbWVudElkcyI6ImRlZmF1bHQsZGVmYXVsdCIsImV4cCI6MjM0ODUwMTY4MCwiaXNzIjoiSFVCIiwiYXVkIjoiSFVCLUFVRElFTkNFIn0.NzadcNu0hrjjxb1YJzHUAyLCJGfBdy7xcm9vXo5_ZbuCGLqMO4teUkVfjvRkcI7innT8mGJR_sHqvsjtMBix8A",
}